<?php

namespace AppBundle\Repository\Entity;

/**
 * PubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubsRepository extends \Doctrine\ORM\EntityRepository
{
}
